# Generated by Django 4.0 on 2024-03-11 07:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_myuser_options_alter_pointdevente_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointdevente',
            old_name='lieu',
            new_name='lieu_pdv',
        ),
        migrations.RenameField(
            model_name='pointdevente',
            old_name='tel',
            new_name='tel_pdv',
        ),
        migrations.AddField(
            model_name='pointdevente',
            name='username_pdv',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='password',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
